permalink: pretty
paginate: 5
markdown: kramdown
author_email: alvarobp@alvarobp.com

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - TODO
  - tmp
  - tasks

javascripts:
  - jquery.js
  - jquery.example.js
  - jquery.lightbox.js
  - syntax_highlighter/shCore.js
  - syntax_highlighter/shBrushCpp.js
  - syntax_highlighter/shBrushCSharp.js
  - syntax_highlighter/shBrushCss.js
  - syntax_highlighter/shBrushDelphi.js
  - syntax_highlighter/shBrushJava.js
  - syntax_highlighter/shBrushJScript.js
  - syntax_highlighter/shBrushPhp.js
  - syntax_highlighter/shBrushPython.js
  - syntax_highlighter/shBrushRuby.js
  - syntax_highlighter/shBrushSql.js
  - syntax_highlighter/shBrushVb.js
  - syntax_highlighter/shBrushXml.js
